Repository mozilla-mobile/firefox-ios, pull requests merged in 2019-10, with the labels that each got.

#5513 Fix Bug 1584757 - Update mozilla/application-services version in Cartfile
  Cartfile
Labels: xcode11

#5514 Fix #5476 - Support switching to opposite UA for iPad and iPhone
  Client.xcodeproj/project.pbxproj
  Client/Application/TestAppDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
  Client/Frontend/Browser/Tab+ChangeUserAgent.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/TabLocationView.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/Settings/Clearables.swift
  Client/Frontend/Widgets/PhotonActionSheet/PageActionMenu.swift
  Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheetProtocol.swift
  ClientTests/ClientTests.swift
  Shared/UserAgent.swift
Labels: xcode11

#5660 Fix #5644 - Remove unnecessary use of Privileged Request
  Client/Application/AppDelegate.swift
  Client/Application/NavigationRouter.swift
  Client/Application/QuickActions.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
  Client/Frontend/InternalSchemeHandler/ErrorPageHelper.swift
  Client/Frontend/Widgets/PhotonActionSheet/TrackingProtectionMenu.swift
Labels: 3

#5674 Fix #5495 - Address bar access with voice control
  Client/Frontend/Browser/TabLocationView.swift
Labels: 1
