Repository mozilla-mobile/firefox-ios, pull requests merged in 2023-06, with the labels that each got.

#14948 Bugfix FXIOS-6695 [v115] Fix show tour to appear under debug menu
  Client/Frontend/Settings/AppSettingsOptions.swift
  Client/Frontend/Settings/AppSettingsTableViewController.swift
Labels: Needs Landing (Squash)

#14998 Bump [v116] Update Glean to v53.0.0
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  bin/sdk_generator.sh
Labels: Needs Landing (Squash)

#15266 Bump [v116] Update Sentry to version 8.8.0
  BrowserKit/Package.swift
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Code Review

#15237 Bugfix MTE-1054 [v116] Re-enable Performance Tests
  Client.xcodeproj/project.pbxproj
  Tests/Fennec_Enterprise_XCUITests.xctestplan
  Tests/SmokeXCUITests.xctestplan
  Tests/Smoketest2.xctestplan
  Tests/Smoketest3.xctestplan
  Tests/Smoketest4.xctestplan
  Tests/XCUITests/DatabaseFixtureTest.swift
  Tests/XCUITests/JumpBackInTests.swift
  Tests/XCUITests/PerformanceTests.swift
  test-fixtures/testHistoryDatabase100-places.db
Labels: Do Not Merge ⛔️
