Repository mozilla-mobile/firefox-ios, pull requests merged in 2023-10, with the labels that each got.

#16600 Build FXIOS-16599 - Switch Taskcluster pull request policy to `public…
  .taskcluster.yml
Labels: eng:automation, Needs Landing

#16804 Bump [v120] Update KIF to version 3.8.9
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#16803 Bump [v120] Update Kingfisher to version 7.9.1
  BrowserKit/Package.swift
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SampleComponentLibraryApp/SampleComponentLibraryApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Code Review

#16800 Bump [v120] Update Sentry to version 8.13.1
  BrowserKit/Package.swift
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#16818 Bump FXIOS-7566 DISCO-2637 [v120] Update uses of `SuggestionQuery`.
  Storage/Rust/RustFirefoxSuggest.swift
Labels: Do Not Merge ⛔️

#16894 Refactor FXIOS-7592 [v120] Update swiftlint to use only rules
  .swiftlint.yml
Labels: Do Not Merge ⛔️

#17000 Bump [v121] Update taskcluster requirements
  taskcluster/requirements.in
  taskcluster/requirements.txt
Labels: Needs Landing (Squash)
