Repository mozilla-mobile/firefox-ios, pull requests merged in 2024-02, with the labels that each got.

#18514 Bump [v124] Update Kingfisher to version 7.10.2
  BrowserKit/Package.swift
  SampleBrowser/SampleBrowser.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SampleComponentLibraryApp/SampleComponentLibraryApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#18510 Bump [v124] Update Sentry to version 8.20.0
  BrowserKit/Package.swift
  SampleBrowser/SampleBrowser.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SampleComponentLibraryApp/SampleComponentLibraryApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#18511 Bump [v124] Update SnapKit to version 5.7.0
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#18512 Bump [v124] Update Adjust SDK to version 4.37.0
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#18363 Add MTE-2230 [v124] iOS Monorepo: Implement a workflow to determine which application to run in bitrise.yml file
  bitrise.yml
Labels: Needs Code Review

#18659 Revert FXIOS-8415 [v123] Revert homepage changes
  firefox-ios/Client/Frontend/Browser/BrowserViewController/Views/BrowserViewController.swift
  firefox-ios/Client/Frontend/Home/CustomizeHome/CustomizeHomepageSectionViewModel.swift
  firefox-ios/Client/Frontend/Home/HistoryHighlights/HistoryHighlightsViewModel.swift
  firefox-ios/Client/Frontend/Home/HomepageViewController.swift
  firefox-ios/Client/Frontend/Home/HomepageViewModel.swift
  firefox-ios/Client/Frontend/Home/HomepageViewModelProtocol.swift
  firefox-ios/Client/Frontend/Home/JumpBackIn/JumpBackInSectionLayout.swift
  firefox-ios/Client/Frontend/Home/JumpBackIn/JumpBackInViewModel.swift
  firefox-ios/Client/Frontend/Home/LogoHeader/HomeLogoHeaderViewModel.swift
  firefox-ios/Client/Frontend/Home/MessageCard/HomepageMessageCardViewModel.swift
  firefox-ios/Client/Frontend/Home/Pocket/PocketViewModel.swift
  firefox-ios/Client/Frontend/Home/RecentlySaved/RecentlySavedViewModel.swift
  firefox-ios/Client/Frontend/Home/TopSites/TopSitesViewModel.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Frontend/Home/JumpBackIn/JumpBackInViewModelTests.swift
Labels: Needs Landing (Squash)

#18813 Bugfix FXIOS-8426 [v124] Fix contextual tabs showing incorrectly in Inactive Tabs section
  firefox-ios/Client/TabManagement/Tab.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/TabManagement/TabManagerTests.swift
Labels: Do Not Merge ⛔️

#18690 Refactor FXIOS-8428 [v125] Use single name field for addresses & update SPM with latest rust-component 125.0.20240226160923
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  firefox-ios/Client/Frontend/Autofill/Address/AddressCellView.swift
  firefox-ios/Client/Frontend/Autofill/Address/AddressListViewModel.swift
  firefox-ios/firefox-ios-tests/Tests/StorageTests/RustAutofillTests.swift
Labels: Do Not Merge ⛔️
