Repository mozilla-mobile/firefox-ios, pull requests merged in 2024-01, with the labels that each got.

#17954 Revert FXIOS-8052 [v121] logins key logic updates
  firefox-ios/Providers/RustSyncManager.swift
  firefox-ios/Shared/Prefs.swift
  firefox-ios/Storage/Rust/RustLogins.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/PasswordManagerViewModelTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/RustSyncManagerTests.swift
  firefox-ios/firefox-ios-tests/Tests/StorageTests/RustLoginsTests.swift
  firefox-ios/firefox-ios-tests/Tests/UnitTest.xctestplan
Labels: Needs Landing (Squash)

#18060 Refactor FXIOS-8107 [v121.2] Disable recently visited section and loading of the history highlights
  BrowserKit/Sources/Common/Extensions/URLExtension.swift
  firefox-ios/Client/Frontend/Home/HistoryHighlights/HistoryHighlightsDataAdaptor.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Coordinators/ShortcutRouteTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/FeatureFlagManagerTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Frontend/Home/HistoryHighlights/HistoryHighlightsDataAdaptorTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Frontend/Home/HistoryHighlights/HistoryHighlightsViewModelTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Messaging/GleanPlumbMessageManagerTests.swift
  firefox-ios/firefox-ios-tests/Tests/ExperimentIntegrationTests.xctestplan
  firefox-ios/firefox-ios-tests/Tests/UnitTest.xctestplan
  firefox-ios/firefox-ios-tests/Tests/XCUITests/HomePageSettingsUITest.swift
  firefox-ios/nimbus-features/homescreenFeature.yaml
Labels: Needs Landing (Squash)

#18101 Build FXIOS-8134 [v123] Upgrade Taskgraph to v7.x + update deps
  .gitignore
  .taskcluster.yml
  taskcluster/config.yml
  taskcluster/ffios_taskgraph/job.py
  taskcluster/ffios_taskgraph/target_tasks.py
  taskcluster/kinds/bitrise-performance/kind.yml
  taskcluster/kinds/build/kind.yml
  taskcluster/kinds/docker-image/kind.yml
  taskcluster/kinds/firebase-performance/kind.yml
  taskcluster/kinds/generate-screenshots/kind.yml
  taskcluster/requirements.in
  taskcluster/requirements.txt
Labels: eng:automation

#18167 Refactor FXIOS-7587 [v123] Replace Padded switch in BoolSetting
  firefox-ios/Client/Frontend/Settings/NotificationsSettingsViewController.swift
  firefox-ios/Client/Frontend/Settings/SearchSettingsTableViewController.swift
  firefox-ios/Client/Frontend/Settings/SettingsTableViewController.swift
Labels: Contributor Fix

#18260 Bump [v122] Set version to 122.1
  Client/Info.plist
  CredentialProvider/Info.plist
  Extensions/NotificationService/Info.plist
  Extensions/ShareTo/Info.plist
  WidgetKit/Info.plist
  bitrise.yml
Labels: Needs Landing (Squash)

#18286 Upgrades appservices to 123.0.0
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#18406 Bugfix FXIOS-8296 [v124] Fix data format issues for credit cards when autofilling
  firefox-ios/Client/Frontend/TabContentsScripts/FormAutofillHelper/FormAutofillHelper.swift
  firefox-ios/Client/Frontend/UserContent/UserScripts/AllFrames/AutofillAtDocumentStart/FormAutofillHelper.js
  firefox-ios/firefox-ios-tests/Tests/ClientTests/CreditCard/CreditCardHelperTests.swift
Labels: Needs Landing (Squash), credit-card-autofill
