Repository mozilla-mobile/firefox-ios, pull requests merged in 2024-09, with the labels that each got.

#21668 Build FXIOS-9877 - upgrade Taskgraph and dependencies to latest versions
  taskcluster/ffios_taskgraph/screenshots_locales.py
  taskcluster/requirements.txt
Labels: eng:automation, Dependencies

#21824 Bugfix FXIOS-9939 ⁃ Tracking Protection Certificates Screen TableView Header is overlapped with TableView content
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client/Frontend/TrackingProtection/CertificatesHeaderView.swift
  firefox-ios/Client/Frontend/TrackingProtection/CertificatesViewController.swift
Labels: Do Not Merge ⛔️

#22255 Bump - Update Glean to version 61.1.0
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  focus-ios/Blockzilla.xcodeproj/project.pbxproj
  focus-ios/Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#22257 Bump - Update SPM to rust-components 132.0.0
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  focus-ios/Blockzilla.xcodeproj/project.pbxproj
  focus-ios/Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)
