Repository mozilla-mobile/firefox-ios, pull requests merged in 2024-12, with the labels that each got.

#23494 Bugfix FXIOS-10740 workaround for crashing on non-unique Sites in the HistoryPanel
  BrowserKit/Sources/SiteImageView/Entities/SiteResource.swift
  BrowserKit/Sources/WebEngine/WKWebview/WKEngineSession.swift
  firefox-ios/Storage/Rust/RustPlaces.swift
  firefox-ios/Storage/Site.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/TestHistory.swift
  firefox-ios/firefox-ios-tests/Tests/XCUITests/HistoryTests.swift
Labels: Do Not Merge ⛔️

#23426 Added FXIOS-10710 default browser telemetry
  bitrise.yml
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  firefox-ios/Client/Application/AppLaunchUtil.swift
  firefox-ios/Client/Application/DefaultBrowserUtil.swift
  firefox-ios/Client/Telemetry/TelemetryWrapper.swift
  firefox-ios/Client/Utils/LocaleInterface.swift
  firefox-ios/Client/Utils/UIApplicationInterface.swift
  firefox-ios/Client/metrics.yaml
  firefox-ios/Shared/Prefs.swift
  firefox-ios/Storage/Rust/RustFirefoxSuggest.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Application/AppSendTabDelegateTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Application/DefaultBrowserUitTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Application/MockLocale.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Application/MockUIApplication.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Mocks/MockUserDefaults.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/TelemetryWrapperTests.swift
  test-fixtures/generate-metrics.sh
Labels: Do Not Merge ⛔️

#23561 Bump FXIOS [Dependencies] Glean v63.0.0 & AppServices v135.0.20241212150752
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  firefox-ios/Client/Telemetry/GleanWrapper.swift
  firefox-ios/bin/sdk_generator.sh
  firefox-ios/firefox-ios-tests/Tests/ClientTests/BrowserViewControllerTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/ContextMenuHelperTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Frontend/Home/Pocket/PocketViewModelTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/MainMenu/MainMenuMiddlewareTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Messaging/GleanPlumbMessageManagerTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Microsurvey/MicrosurveyMiddlewareTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/OnboardingTests/OnboardingTelemetryDelegationTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/OnboardingTests/OnboardingTelemetryUtilityTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/PasswordGenerator/PasswordGeneratorTelemetryTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/PasswordManagerViewModelTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/PrivateBrowsingTelemetryTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/SponsoredTileTelemetryTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/TabManagement/Legacy/TabsTelemetryTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/TabToolbarHelperTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/TabTray/InactiveTabsTelemetryTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Telemetry/HomepageTelemetryTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Telemetry/MainMenuTelemetryTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Telemetry/ToolbarTelemetryTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/TelemetryContextualIdentifierTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/TelemetryWrapperTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Wallpaper/WallpaperSelectorViewModelTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Wallpaper/WallpaperSettingsViewModelTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/WebviewTelemetryTests.swift
  focus-ios/Blockzilla.xcodeproj/project.pbxproj
  focus-ios/Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  focus-ios/Blockzilla/Settings/Controller/SettingsViewController.swift
  focus-ios/bin/sdk_generator.sh
Labels: Do Not Merge ⛔️, Do not stale

#23972 Bugfix FXIOS-10969 - [Toolbar Redesign] - Can't type Chinese/Japanese in search bar
  BrowserKit/Sources/ToolbarKit/AddressToolbar/LocationView/LocationTextField.swift
Labels: weekly-release
