Repository mozilla-mobile/firefox-ios, pull requests merged in 2025-01, with the labels that each got.

#23898 Bump - Set version to 134.1
  bitrise.yml
  firefox-ios/Client/Info.plist
  firefox-ios/CredentialProvider/Info.plist
  firefox-ios/Extensions/NotificationService/Info.plist
  firefox-ios/Extensions/ShareTo/Info.plist
  firefox-ios/WidgetKit/Info.plist
  focus-ios/Blockzilla/Info.plist
  focus-ios/ContentBlocker/Info.plist
  focus-ios/FocusIntentExtension/Info.plist
  focus-ios/OpenInFocus/Info.plist
  focus-ios/Widgets/Info.plist
Labels: stale

#24005 Bump - Set version to 136.0
  bitrise.yml
  firefox-ios/Client/Info.plist
  firefox-ios/CredentialProvider/Info.plist
  firefox-ios/Extensions/NotificationService/Info.plist
  firefox-ios/Extensions/ShareTo/Info.plist
  firefox-ios/WidgetKit/Info.plist
  focus-ios/Blockzilla/Info.plist
  focus-ios/ContentBlocker/Info.plist
  focus-ios/FocusIntentExtension/Info.plist
  focus-ios/OpenInFocus/Info.plist
  focus-ios/Widgets/Info.plist
Labels: Needs Landing (Squash)

#23880 Refactor FXIOS-10205 [Swiftlint] Resolve 13 implicitly_unwrapped_optional violations in Client/TabManagement
  firefox-ios/Client/TabManagement/Legacy/LegacyTabManager.swift
  firefox-ios/Client/TabManagement/TabManager.swift
  firefox-ios/Client/TabManagement/TabManagerNavDelegate.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Mocks/MockTabManager.swift
Labels: Contributor Fix

#23812 Add FXIOS-10683 Focus iOS: Add new setting to control crash reporting
  focus-ios/Blockzilla/AppDelegate.swift
  focus-ios/Blockzilla/Settings/Controller/SettingsViewController.swift
  focus-ios/Blockzilla/Utilities/SupportUtils.swift
  focus-ios/Shared/Settings.swift
Labels: stale

#24108 Refactor FXIOS-10788 [Logins] Apply necessary adjustments for A-S EncryptorDecryptor update
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  firefox-ios/Client/Coordinators/CredentialAutofillCoordinator.swift
  firefox-ios/Client/Frontend/Autofill/LoginCellView.swift
  firefox-ios/Client/Frontend/Autofill/LoginListViewModel.swift
  firefox-ios/Client/Frontend/Autofill/LoginStorage.swift
  firefox-ios/Client/Frontend/Browser/Authenticator.swift
  firefox-ios/Client/Frontend/Browser/BrowserViewController/Views/BrowserViewController.swift
  firefox-ios/Client/Frontend/PasswordManagement/AddCredentialViewController.swift
  firefox-ios/Client/Frontend/PasswordManagement/LoginDataSource.swift
  firefox-ios/Client/Frontend/PasswordManagement/LoginProvider.swift
  firefox-ios/Client/Frontend/PasswordManagement/PasswordManagerSelectionHelper.swift
  firefox-ios/Client/Frontend/PasswordManagement/PasswordManagerViewModel.swift
  firefox-ios/Client/Frontend/Settings/PasswordDetailViewController.swift
  firefox-ios/Client/Frontend/TabContentsScripts/LoginsHelper.swift
  firefox-ios/Providers/LoginRecordExtension.swift
  firefox-ios/Storage/MockMZKeychainWrapper.swift
  firefox-ios/Storage/Rust/RustLogins.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Autofill/LoginListViewModelTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Autofill/Mocks/MockLoginProvider.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/Coordinators/CredentialAutofillCoordinatorTests.swift
  firefox-ios/firefox-ios-tests/Tests/ClientTests/PasswordManagerSelectionHelperTests.swift
  firefox-ios/firefox-ios-tests/Tests/StorageTests/RustLoginsTests.swift
  firefox-ios/firefox-ios-tests/Tests/XCUITests/LoginsTests.swift
  focus-ios/Blockzilla.xcodeproj/project.pbxproj
  focus-ios/Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Do Not Merge ⛔️

#24427 Bugfix FXIOS-11228 Settings height bug
  firefox-ios/Client/Frontend/Settings/Main/AppSettingsTableViewController.swift
Labels: Needs Landing (Squash)
