Repository mozilla-mobile/firefox-ios, pull requests merged in 2025-03, with the labels that each got.

#25002 Bugfix FXIOS-10852 ⁃ [iPad] - Weird behavior of tabs after a specific scenario
  firefox-ios/Client/Frontend/Browser/Tabs/Middleware/TabManagerMiddleware.swift
Labels: Do Not Merge ⛔️

#25370 Revert FXIOS-11466 [App Icon 2025] v136 Only Revert Add Blue Gradient and Orange Gradient App Icons for App Store A/B Experiment
  firefox-ios/Client.xcodeproj/project.pbxproj
  firefox-ios/Client/Assets/AppIcons.xcassets/AppIcon_Alt_BlueGradient.appiconset/AppIcon_Alt_Tinted.png
  firefox-ios/Client/Assets/AppIcons.xcassets/AppIcon_Alt_BlueGradient.appiconset/Blue-Gradient-Icon-Dark.png
  firefox-ios/Client/Assets/AppIcons.xcassets/AppIcon_Alt_BlueGradient.appiconset/Blue-Gradient-Icon-Light.png
  firefox-ios/Client/Assets/AppIcons.xcassets/AppIcon_Alt_BlueGradient.appiconset/Contents.json
  firefox-ios/Client/Assets/AppIcons.xcassets/AppIcon_Alt_OrangeGradient.appiconset/AppIcon_Alt_Tinted.png
  firefox-ios/Client/Assets/AppIcons.xcassets/AppIcon_Alt_OrangeGradient.appiconset/Contents.json
  firefox-ios/Client/Assets/AppIcons.xcassets/AppIcon_Alt_OrangeGradient.appiconset/Orange-Gradient-Icon-Dark.png
  firefox-ios/Client/Assets/AppIcons.xcassets/AppIcon_Alt_OrangeGradient.appiconset/Orange-Gradient-Icon-Light.png
  firefox-ios/Client/Assets/AppIcons.xcassets/Contents.json
Labels: weekly-release

#24907 Bugfix FXIOS-11441 [Search engines] Add DuckDuckGo to all locales
  firefox-ios/Client/Assets/Search/SearchPlugins/list.json
  firefox-ios/firefox-ios-tests/Tests/ClientTests/DefaultSearchPrefsTests.swift
Labels: Do not stale

#25598 Bugfix FXIOS-11722 - [Toolbar UI Experiments] - Toolbar is moved to bottom after activating the experiment
  firefox-ios/Client/Frontend/Onboarding/Views/OnboardingMultipleChoiceCardViewController.swift
Labels: weekly-release
